handlers= java.util.logging.ConsoleHandler
.level = INFO

java.util.logging.FileHandler.pattern = log/mas-%g.log
java.util.logging.FileHandler.limit = 500000
java.util.logging.FileHandler.count = 10
java.util.logging.FileHandler.formatter = jason.runtime.MASConsoleLogFormatter

java.util.logging.ConsoleHandler.level = FINE
java.util.logging.ConsoleHandler.formatter = jason.runtime.MASConsoleLogFormatter

java.level=OFF
javax.level=OFF
sun.level=OFF
jade.level=OFF
